import { z } from 'zod'
export const AccountsSourceCreateAccountSourceBodySchema = z.object({ "accountId": z.string(), "source": z.string() })
export const AccountsSourceCreateAccountSourceResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const AccountsSourceGetAccountSourceBodySchema = z.unknown()
export const AccountsSourceGetAccountSourceResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const AccountsSourceGetAccountSourceByIdBodySchema = z.unknown()
export const AccountsSourceGetAccountSourceByIdResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const AccountsSourceUpdateAccountSourceByIdBodySchema = z.object({ "accountId": z.string().optional(), "source": z.string().optional() })
export const AccountsSourceUpdateAccountSourceByIdResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const AccountsSourceDeleteAccountSourceByIdBodySchema = z.unknown()
export const AccountsSourceDeleteAccountSourceByIdResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const AccountsSourceGetAccountSourceByAccountBodySchema = z.unknown()
export const AccountsSourceGetAccountSourceByAccountResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })