import { z } from 'zod'
export const AccountsBalanceCreateAccountBalanceBodySchema = z.object({ "accountId": z.string(), "date": z.string(), "balance": z.number() })
export const AccountsBalanceCreateAccountBalanceResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const AccountsBalanceGetAccountBalanceBodySchema = z.unknown()
export const AccountsBalanceGetAccountBalanceResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const AccountsBalanceGetAccountBalanceByIdBodySchema = z.unknown()
export const AccountsBalanceGetAccountBalanceByIdResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const AccountsBalanceUpdateAccountBalanceByIdBodySchema = z.object({ "accountId": z.string().optional(), "date": z.string().optional(), "balance": z.number().optional() })
export const AccountsBalanceUpdateAccountBalanceByIdResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const AccountsBalanceDeleteAccountBalanceByIdBodySchema = z.unknown()
export const AccountsBalanceDeleteAccountBalanceByIdResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const AccountsBalanceGetAccountBalanceByAccountBodySchema = z.unknown()
export const AccountsBalanceGetAccountBalanceByAccountResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })