import { z } from 'zod'
export const AuthGetCsrfTokenBodySchema = z.unknown()
export const AuthGetCsrfTokenResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const AuthCreateLoginBodySchema = z.object({ "email": z.string(), "password": z.string() })
export const AuthCreateLoginResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "data": z.object({ "token": z.string(), "user": z.object({ "name": z.string(), "surname": z.string(), "email": z.string(), "password": z.string(), "contact": z.string(), "id": z.string(), "createdAt": z.union([z.string()]), "updatedAt": z.union([z.string()]).optional() }) }) })
export const AuthCreateRefreshTokenBodySchema = z.unknown()
export const AuthCreateRefreshTokenResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const AuthCreateLogoutBodySchema = z.unknown()
export const AuthCreateLogoutResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const AuthCreateForgotPasswordBodySchema = z.object({ "email": z.string() })
export const AuthCreateForgotPasswordResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const AuthCreateResetPasswordBodySchema = z.object({ "token": z.string(), "newPassword": z.string(), "confirmPassword": z.string() })
export const AuthCreateResetPasswordResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const AuthCreateVerifyResetTokenBodySchema = z.object({ "token": z.string() })
export const AuthCreateVerifyResetTokenResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const AuthGetResetPasswordByTokenBodySchema = z.unknown()
export const AuthGetResetPasswordByTokenResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })