import { z } from 'zod'
export const BanksCreateBodySchema = z.object({ "bankName": z.string(), "logoUrl": z.union([z.string(), z.null()]).optional() })
export const BanksCreateResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "data": z.object({ "bankName": z.string(), "logoUrl": z.union([z.string(), z.null()]).optional(), "id": z.string().optional() }) })
export const BanksGetBodySchema = z.unknown()
export const BanksGetResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "data": z.array(z.object({ "bankName": z.string(), "logoUrl": z.union([z.string(), z.null()]).optional(), "id": z.string().optional() })) })
export const BanksGetByIdBodySchema = z.unknown()
export const BanksGetByIdResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "data": z.object({ "bankName": z.string(), "logoUrl": z.union([z.string(), z.null()]).optional(), "id": z.string().optional() }) })
export const BanksUpdateByIdBodySchema = z.object({ "bankName": z.string().optional(), "logoUrl": z.union([z.string(), z.null()]).optional() })
export const BanksUpdateByIdResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "data": z.object({ "bankName": z.string(), "logoUrl": z.union([z.string(), z.null()]).optional(), "id": z.string().optional() }) })
export const BanksDeleteByIdBodySchema = z.unknown()
export const BanksDeleteByIdResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "data": z.null().optional() })