import { z } from 'zod'
export const IncomesPostIncomeBodySchema = z.object({ "description": z.string(), "amount": z.number(), "sourceId": z.string(), "accountId": z.string().optional(), "date": z.string(), "userId": z.string() })
export const IncomesPostIncomeResponseSchema = z.unknown()
export const IncomesGetIncomeBodySchema = z.unknown()
export const IncomesGetIncomeResponseSchema = z.unknown()
export const IncomesGetIncomeByIdBodySchema = z.unknown()
export const IncomesGetIncomeByIdResponseSchema = z.unknown()
export const IncomesPutIncomeByIdBodySchema = z.object({ "description": z.string().optional(), "amount": z.number().optional(), "sourceId": z.string().optional(), "accountId": z.string().optional(), "date": z.string().optional(), "userId": z.string().optional() })
export const IncomesPutIncomeByIdResponseSchema = z.unknown()
export const IncomesDeleteIncomeByIdBodySchema = z.unknown()
export const IncomesDeleteIncomeByIdResponseSchema = z.unknown()
export const IncomesGetIncomeUserByUserIdBodySchema = z.unknown()
export const IncomesGetIncomeUserByUserIdResponseSchema = z.unknown()
export const IncomesGetIncomeSourceBySourceIdBodySchema = z.unknown()
export const IncomesGetIncomeSourceBySourceIdResponseSchema = z.unknown()