import { z } from 'zod'
export const ReportsGetDashboardBodySchema = z.unknown()
export const ReportsGetDashboardResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const ReportsGetEvolutionBodySchema = z.unknown()
export const ReportsGetEvolutionResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const ReportsGetCashFlowBodySchema = z.unknown()
export const ReportsGetCashFlowResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const ReportsGetNetWorthBodySchema = z.unknown()
export const ReportsGetNetWorthResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const ReportsGetExpenseAnalysisBodySchema = z.unknown()
export const ReportsGetExpenseAnalysisResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const ReportsGetIncomeAnalysisBodySchema = z.unknown()
export const ReportsGetIncomeAnalysisResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const ReportsGetFinancialHealthBodySchema = z.unknown()
export const ReportsGetFinancialHealthResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })
export const ReportsGetBudgetVsActualBodySchema = z.unknown()
export const ReportsGetBudgetVsActualResponseSchema = z.object({ "success": z.boolean(), "message": z.string(), "errors": z.array(z.object({ "message": z.string(), "path": z.array(z.string()).optional() })).optional() })