import { z } from 'zod'
export const ReportsGetReportsDashboardBodySchema = z.unknown()
export const ReportsGetReportsDashboardResponseSchema = z.unknown()
export const ReportsGetReportsEvolutionBodySchema = z.unknown()
export const ReportsGetReportsEvolutionResponseSchema = z.unknown()
export const ReportsGetReportsCashFlowBodySchema = z.unknown()
export const ReportsGetReportsCashFlowResponseSchema = z.unknown()
export const ReportsGetReportsNetWorthBodySchema = z.unknown()
export const ReportsGetReportsNetWorthResponseSchema = z.unknown()
export const ReportsGetReportsExpenseAnalysisBodySchema = z.unknown()
export const ReportsGetReportsExpenseAnalysisResponseSchema = z.unknown()
export const ReportsGetReportsIncomeAnalysisBodySchema = z.unknown()
export const ReportsGetReportsIncomeAnalysisResponseSchema = z.unknown()
export const ReportsGetReportsFinancialHealthBodySchema = z.unknown()
export const ReportsGetReportsFinancialHealthResponseSchema = z.unknown()
export const ReportsGetReportsBudgetVsActualBodySchema = z.unknown()
export const ReportsGetReportsBudgetVsActualResponseSchema = z.unknown()