export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'
export interface RouteDef {
  tag: string
  method: HttpMethod
  path: string
  name: string
}
export const AuthRoutes: RouteDef[] = [
  {
    tag: 'Auth',
    method: 'GET',
    path: '/auth/csrf-token',
    name: 'AuthGetAuthCsrfToken',
  },
  {
    tag: 'Auth',
    method: 'POST',
    path: '/auth/login',
    name: 'AuthPostAuthLogin',
  },
  {
    tag: 'Auth',
    method: 'POST',
    path: '/auth/refresh-token',
    name: 'AuthPostAuthRefreshToken',
  },
  {
    tag: 'Auth',
    method: 'POST',
    path: '/auth/logout',
    name: 'AuthPostAuthLogout',
  },
  {
    tag: 'Auth',
    method: 'POST',
    path: '/auth/forgot-password',
    name: 'AuthPostAuthForgotPassword',
  },
  {
    tag: 'Auth',
    method: 'POST',
    path: '/auth/reset-password',
    name: 'AuthPostAuthResetPassword',
  },
]
export const UsersRoutes: RouteDef[] = [
  { tag: 'Users', method: 'POST', path: '/users', name: 'UsersPostUsers' },
  { tag: 'Users', method: 'GET', path: '/users', name: 'UsersGetUsers' },
  {
    tag: 'Users',
    method: 'GET',
    path: '/users/{id}',
    name: 'UsersGetUsersById',
  },
  {
    tag: 'Users',
    method: 'PUT',
    path: '/users/{id}',
    name: 'UsersPutUsersById',
  },
  {
    tag: 'Users',
    method: 'DELETE',
    path: '/users/{id}',
    name: 'UsersDeleteUsersById',
  },
  {
    tag: 'Users',
    method: 'GET',
    path: '/users/{id}/profile',
    name: 'UsersGetUsersByIdProfile',
  },
]
export const AccountsRoutes: RouteDef[] = [
  {
    tag: 'Accounts',
    method: 'POST',
    path: '/accounts',
    name: 'AccountsPostAccounts',
  },
  {
    tag: 'Accounts',
    method: 'GET',
    path: '/accounts',
    name: 'AccountsGetAccounts',
  },
  {
    tag: 'Accounts',
    method: 'GET',
    path: '/accounts/{id}',
    name: 'AccountsGetAccountsById',
  },
  {
    tag: 'Accounts',
    method: 'PUT',
    path: '/accounts/{id}',
    name: 'AccountsPutAccountsById',
  },
  {
    tag: 'Accounts',
    method: 'DELETE',
    path: '/accounts/{id}',
    name: 'AccountsDeleteAccountsById',
  },
  {
    tag: 'Accounts',
    method: 'GET',
    path: '/accounts/{id}/transactions',
    name: 'AccountsGetAccountsByIdTransactions',
  },
  {
    tag: 'Accounts',
    method: 'GET',
    path: '/accounts/default/{userId}',
    name: 'AccountsGetAccountsDefaultByUserId',
  },
  {
    tag: 'Accounts',
    method: 'GET',
    path: '/account/{userId}',
    name: 'AccountsGetAccountByUserId',
  },
]
export const AccountsBalanceRoutes: RouteDef[] = [
  {
    tag: 'Accounts Balance',
    method: 'POST',
    path: '/account-balance',
    name: 'AccountsBalancePostAccountBalance',
  },
  {
    tag: 'Accounts Balance',
    method: 'GET',
    path: '/account-balance',
    name: 'AccountsBalanceGetAccountBalance',
  },
  {
    tag: 'Accounts Balance',
    method: 'GET',
    path: '/account-balance/{id}',
    name: 'AccountsBalanceGetAccountBalanceById',
  },
  {
    tag: 'Accounts Balance',
    method: 'PUT',
    path: '/account-balance/{id}',
    name: 'AccountsBalancePutAccountBalanceById',
  },
  {
    tag: 'Accounts Balance',
    method: 'DELETE',
    path: '/account-balance/{id}',
    name: 'AccountsBalanceDeleteAccountBalanceById',
  },
  {
    tag: 'Accounts Balance',
    method: 'GET',
    path: '/account-balance/account/{accountId}',
    name: 'AccountsBalanceGetAccountBalanceAccountByAccountId',
  },
]
export const AccountsSourceRoutes: RouteDef[] = [
  {
    tag: 'Accounts Source',
    method: 'POST',
    path: '/account-source',
    name: 'AccountsSourcePostAccountSource',
  },
  {
    tag: 'Accounts Source',
    method: 'GET',
    path: '/account-source',
    name: 'AccountsSourceGetAccountSource',
  },
  {
    tag: 'Accounts Source',
    method: 'GET',
    path: '/account-source/{id}',
    name: 'AccountsSourceGetAccountSourceById',
  },
  {
    tag: 'Accounts Source',
    method: 'PUT',
    path: '/account-source/{id}',
    name: 'AccountsSourcePutAccountSourceById',
  },
  {
    tag: 'Accounts Source',
    method: 'DELETE',
    path: '/account-source/{id}',
    name: 'AccountsSourceDeleteAccountSourceById',
  },
  {
    tag: 'Accounts Source',
    method: 'GET',
    path: '/account-source/account/{accountId}',
    name: 'AccountsSourceGetAccountSourceAccountByAccountId',
  },
]
export const BanksRoutes: RouteDef[] = [
  { tag: 'Banks', method: 'POST', path: '/banks', name: 'BanksPostBanks' },
  { tag: 'Banks', method: 'GET', path: '/banks', name: 'BanksGetBanks' },
  {
    tag: 'Banks',
    method: 'GET',
    path: '/banks/{id}',
    name: 'BanksGetBanksById',
  },
  {
    tag: 'Banks',
    method: 'PUT',
    path: '/banks/{id}',
    name: 'BanksPutBanksById',
  },
  {
    tag: 'Banks',
    method: 'DELETE',
    path: '/banks/{id}',
    name: 'BanksDeleteBanksById',
  },
]
export const CategoriesRoutes: RouteDef[] = [
  {
    tag: 'Categories',
    method: 'POST',
    path: '/categories',
    name: 'CategoriesPostCategories',
  },
  {
    tag: 'Categories',
    method: 'GET',
    path: '/categories',
    name: 'CategoriesGetCategories',
  },
  {
    tag: 'Categories',
    method: 'GET',
    path: '/categories/{id}',
    name: 'CategoriesGetCategoriesById',
  },
  {
    tag: 'Categories',
    method: 'PUT',
    path: '/categories/{id}',
    name: 'CategoriesPutCategoriesById',
  },
  {
    tag: 'Categories',
    method: 'DELETE',
    path: '/cateories/{id}',
    name: 'CategoriesDeleteCateoriesById',
  },
]
export const BudgetRoutes: RouteDef[] = [
  { tag: 'Budget', method: 'POST', path: '/budget', name: 'BudgetPostBudget' },
  { tag: 'Budget', method: 'GET', path: '/budget', name: 'BudgetGetBudget' },
  {
    tag: 'Budget',
    method: 'GET',
    path: '/budget/{id}',
    name: 'BudgetGetBudgetById',
  },
  {
    tag: 'Budget',
    method: 'PUT',
    path: '/budget/{id}',
    name: 'BudgetPutBudgetById',
  },
  {
    tag: 'Budget',
    method: 'DELETE',
    path: '/budget/{id}',
    name: 'BudgetDeleteBudgetById',
  },
  {
    tag: 'Budget',
    method: 'GET',
    path: '/budget/user/{userId}',
    name: 'BudgetGetBudgetUserByUserId',
  },
]
export const CreditCardsRoutes: RouteDef[] = [
  {
    tag: 'Credit Cards',
    method: 'POST',
    path: '/credit-cards',
    name: 'CreditCardsPostCreditCards',
  },
  {
    tag: 'Credit Cards',
    method: 'GET',
    path: '/credit-cards',
    name: 'CreditCardsGetCreditCards',
  },
  {
    tag: 'Credit Cards',
    method: 'GET',
    path: '/credit-cards/{id}',
    name: 'CreditCardsGetCreditCardsById',
  },
  {
    tag: 'Credit Cards',
    method: 'PUT',
    path: '/credit-cards/{id}',
    name: 'CreditCardsPutCreditCardsById',
  },
  {
    tag: 'Credit Cards',
    method: 'DELETE',
    path: '/credit-cards/{id}',
    name: 'CreditCardsDeleteCreditCardsById',
  },
  {
    tag: 'Credit Cards',
    method: 'GET',
    path: '/credit-cards/user/{userId}',
    name: 'CreditCardsGetCreditCardsUserByUserId',
  },
]
export const DebtsRoutes: RouteDef[] = [
  { tag: 'Debts', method: 'POST', path: '/debts', name: 'DebtsPostDebts' },
  { tag: 'Debts', method: 'GET', path: '/debts', name: 'DebtsGetDebts' },
  {
    tag: 'Debts',
    method: 'GET',
    path: '/debts/{id}',
    name: 'DebtsGetDebtsById',
  },
  {
    tag: 'Debts',
    method: 'PUT',
    path: '/debts/{id}',
    name: 'DebtsPutDebtsById',
  },
  {
    tag: 'Debts',
    method: 'DELETE',
    path: '/debts/{id}',
    name: 'DebtsDeleteDebtsById',
  },
  {
    tag: 'Debts',
    method: 'GET',
    path: '/debts/user/{userId}',
    name: 'DebtsGetDebtsUserByUserId',
  },
]
export const DebtPaymentsRoutes: RouteDef[] = [
  {
    tag: 'Debt Payments',
    method: 'POST',
    path: '/debt-payments',
    name: 'DebtPaymentsPostDebtPayments',
  },
  {
    tag: 'Debt Payments',
    method: 'GET',
    path: '/debt-payments',
    name: 'DebtPaymentsGetDebtPayments',
  },
  {
    tag: 'Debt Payments',
    method: 'GET',
    path: '/debt-payments/{id}',
    name: 'DebtPaymentsGetDebtPaymentsById',
  },
  {
    tag: 'Debt Payments',
    method: 'PUT',
    path: '/debt-payments/{id}',
    name: 'DebtPaymentsPutDebtPaymentsById',
  },
  {
    tag: 'Debt Payments',
    method: 'DELETE',
    path: '/debt-payments/{id}',
    name: 'DebtPaymentsDeleteDebtPaymentsById',
  },
  {
    tag: 'Debt Payments',
    method: 'GET',
    path: '/debt-payments/debt/{debtId}',
    name: 'DebtPaymentsGetDebtPaymentsDebtByDebtId',
  },
]
export const ExpensesRoutes: RouteDef[] = [
  {
    tag: 'Expenses',
    method: 'POST',
    path: '/expenses',
    name: 'ExpensesPostExpenses',
  },
  {
    tag: 'Expenses',
    method: 'GET',
    path: '/expenses',
    name: 'ExpensesGetExpenses',
  },
  {
    tag: 'Expenses',
    method: 'GET',
    path: '/expenses/{id}',
    name: 'ExpensesGetExpensesById',
  },
  {
    tag: 'Expenses',
    method: 'PUT',
    path: '/expenses/{id}',
    name: 'ExpensesPutExpensesById',
  },
  {
    tag: 'Expenses',
    method: 'DELETE',
    path: '/expenses/{id}',
    name: 'ExpensesDeleteExpensesById',
  },
  {
    tag: 'Expenses',
    method: 'GET',
    path: '/expenses/user/{userId}',
    name: 'ExpensesGetExpensesUserByUserId',
  },
  {
    tag: 'Expenses',
    method: 'GET',
    path: '/expenses/category/{categoryId}',
    name: 'ExpensesGetExpensesCategoryByCategoryId',
  },
]
export const IncomesRoutes: RouteDef[] = [
  {
    tag: 'Incomes',
    method: 'POST',
    path: '/income',
    name: 'IncomesPostIncome',
  },
  { tag: 'Incomes', method: 'GET', path: '/income', name: 'IncomesGetIncome' },
  {
    tag: 'Incomes',
    method: 'GET',
    path: '/income/{id}',
    name: 'IncomesGetIncomeById',
  },
  {
    tag: 'Incomes',
    method: 'PUT',
    path: '/income/{id}',
    name: 'IncomesPutIncomeById',
  },
  {
    tag: 'Incomes',
    method: 'DELETE',
    path: '/income/{id}',
    name: 'IncomesDeleteIncomeById',
  },
  {
    tag: 'Incomes',
    method: 'GET',
    path: '/income/user/{userId}',
    name: 'IncomesGetIncomeUserByUserId',
  },
  {
    tag: 'Incomes',
    method: 'GET',
    path: '/income/source/{sourceId}',
    name: 'IncomesGetIncomeSourceBySourceId',
  },
]
export const IncomeSourceRoutes: RouteDef[] = [
  {
    tag: 'Income Source',
    method: 'POST',
    path: '/income-source',
    name: 'IncomeSourcePostIncomeSource',
  },
  {
    tag: 'Income Source',
    method: 'GET',
    path: '/income-source',
    name: 'IncomeSourceGetIncomeSource',
  },
  {
    tag: 'Income Source',
    method: 'GET',
    path: '/income-source/{id}',
    name: 'IncomeSourceGetIncomeSourceById',
  },
  {
    tag: 'Income Source',
    method: 'PUT',
    path: '/income-source/{id}',
    name: 'IncomeSourcePutIncomeSourceById',
  },
  {
    tag: 'Income Source',
    method: 'DELETE',
    path: '/income-source/{id}',
    name: 'IncomeSourceDeleteIncomeSourceById',
  },
]
export const DefaultRoutes: RouteDef[] = [
  {
    tag: 'Default',
    method: 'GET',
    path: '/income-sources/user/{userId}',
    name: 'DefaultGetIncomeSourcesUserByUserId',
  },
]
export const InvestmentsRoutes: RouteDef[] = [
  {
    tag: 'Investments',
    method: 'POST',
    path: '/investment',
    name: 'InvestmentsPostInvestment',
  },
  {
    tag: 'Investments',
    method: 'GET',
    path: '/investment',
    name: 'InvestmentsGetInvestment',
  },
  {
    tag: 'Investments',
    method: 'GET',
    path: '/investment/user/{userId}',
    name: 'InvestmentsGetInvestmentUserByUserId',
  },
  {
    tag: 'Investments',
    method: 'PUT',
    path: '/investment/{id}',
    name: 'InvestmentsPutInvestmentById',
  },
  {
    tag: 'Investments',
    method: 'DELETE',
    path: '/investment/{id}',
    name: 'InvestmentsDeleteInvestmentById',
  },
]
export const InvestmentGoalsRoutes: RouteDef[] = [
  {
    tag: 'Investment Goals',
    method: 'POST',
    path: '/investment-goal',
    name: 'InvestmentGoalsPostInvestmentGoal',
  },
  {
    tag: 'Investment Goals',
    method: 'GET',
    path: '/investment-goal',
    name: 'InvestmentGoalsGetInvestmentGoal',
  },
  {
    tag: 'Investment Goals',
    method: 'PUT',
    path: '/investment-goal/{id}',
    name: 'InvestmentGoalsPutInvestmentGoalById',
  },
  {
    tag: 'Investment Goals',
    method: 'DELETE',
    path: '/investment-goal/{id}',
    name: 'InvestmentGoalsDeleteInvestmentGoalById',
  },
]
export const TransactionRoutes: RouteDef[] = [
  {
    tag: 'Transaction',
    method: 'POST',
    path: '/transaction',
    name: 'TransactionPostTransaction',
  },
  {
    tag: 'Transaction',
    method: 'GET',
    path: '/transaction',
    name: 'TransactionGetTransaction',
  },
  {
    tag: 'Transaction',
    method: 'GET',
    path: '/transaction/{id}',
    name: 'TransactionGetTransactionById',
  },
  {
    tag: 'Transaction',
    method: 'PUT',
    path: '/transaction/{id}',
    name: 'TransactionPutTransactionById',
  },
  {
    tag: 'Transaction',
    method: 'DELETE',
    path: '/transaction/{id}',
    name: 'TransactionDeleteTransactionById',
  },
]
export const TransactionsAttachmentRoutes: RouteDef[] = [
  {
    tag: 'Transactions Attachment',
    method: 'POST',
    path: '/transaction-attachment',
    name: 'TransactionsAttachmentPostTransactionAttachment',
  },
  {
    tag: 'Transactions Attachment',
    method: 'GET',
    path: '/transaction-attachment',
    name: 'TransactionsAttachmentGetTransactionAttachment',
  },
  {
    tag: 'Transactions Attachment',
    method: 'GET',
    path: '/transaction-attachment/{id}',
    name: 'TransactionsAttachmentGetTransactionAttachmentById',
  },
  {
    tag: 'Transactions Attachment',
    method: 'PUT',
    path: '/transaction-attachment/{id}',
    name: 'TransactionsAttachmentPutTransactionAttachmentById',
  },
  {
    tag: 'Transactions Attachment',
    method: 'DELETE',
    path: '/transaction-attachment/{id}',
    name: 'TransactionsAttachmentDeleteTransactionAttachmentById',
  },
]
export const ReportsRoutes: RouteDef[] = [
  {
    tag: 'Reports',
    method: 'GET',
    path: '/reports/dashboard',
    name: 'ReportsGetReportsDashboard',
  },
  {
    tag: 'Reports',
    method: 'GET',
    path: '/reports/evolution',
    name: 'ReportsGetReportsEvolution',
  },
]
export const HealthRoutes: RouteDef[] = [
  { tag: 'Health', method: 'GET', path: '/health', name: 'HealthGetHealth' },
]
export const AllRoutes: RouteDef[] = [
  {
    tag: 'Auth',
    method: 'GET',
    path: '/auth/csrf-token',
    name: 'AuthGetAuthCsrfToken',
  },
  {
    tag: 'Auth',
    method: 'POST',
    path: '/auth/login',
    name: 'AuthPostAuthLogin',
  },
  {
    tag: 'Auth',
    method: 'POST',
    path: '/auth/refresh-token',
    name: 'AuthPostAuthRefreshToken',
  },
  {
    tag: 'Auth',
    method: 'POST',
    path: '/auth/logout',
    name: 'AuthPostAuthLogout',
  },
  {
    tag: 'Auth',
    method: 'POST',
    path: '/auth/forgot-password',
    name: 'AuthPostAuthForgotPassword',
  },
  {
    tag: 'Auth',
    method: 'POST',
    path: '/auth/reset-password',
    name: 'AuthPostAuthResetPassword',
  },
  { tag: 'Users', method: 'POST', path: '/users', name: 'UsersPostUsers' },
  { tag: 'Users', method: 'GET', path: '/users', name: 'UsersGetUsers' },
  {
    tag: 'Users',
    method: 'GET',
    path: '/users/{id}',
    name: 'UsersGetUsersById',
  },
  {
    tag: 'Users',
    method: 'PUT',
    path: '/users/{id}',
    name: 'UsersPutUsersById',
  },
  {
    tag: 'Users',
    method: 'DELETE',
    path: '/users/{id}',
    name: 'UsersDeleteUsersById',
  },
  {
    tag: 'Users',
    method: 'GET',
    path: '/users/{id}/profile',
    name: 'UsersGetUsersByIdProfile',
  },
  {
    tag: 'Accounts',
    method: 'POST',
    path: '/accounts',
    name: 'AccountsPostAccounts',
  },
  {
    tag: 'Accounts',
    method: 'GET',
    path: '/accounts',
    name: 'AccountsGetAccounts',
  },
  {
    tag: 'Accounts',
    method: 'GET',
    path: '/accounts/{id}',
    name: 'AccountsGetAccountsById',
  },
  {
    tag: 'Accounts',
    method: 'PUT',
    path: '/accounts/{id}',
    name: 'AccountsPutAccountsById',
  },
  {
    tag: 'Accounts',
    method: 'DELETE',
    path: '/accounts/{id}',
    name: 'AccountsDeleteAccountsById',
  },
  {
    tag: 'Accounts',
    method: 'GET',
    path: '/accounts/{id}/transactions',
    name: 'AccountsGetAccountsByIdTransactions',
  },
  {
    tag: 'Accounts',
    method: 'GET',
    path: '/accounts/default/{userId}',
    name: 'AccountsGetAccountsDefaultByUserId',
  },
  {
    tag: 'Accounts',
    method: 'GET',
    path: '/account/{userId}',
    name: 'AccountsGetAccountByUserId',
  },
  {
    tag: 'Accounts Balance',
    method: 'POST',
    path: '/account-balance',
    name: 'AccountsBalancePostAccountBalance',
  },
  {
    tag: 'Accounts Balance',
    method: 'GET',
    path: '/account-balance',
    name: 'AccountsBalanceGetAccountBalance',
  },
  {
    tag: 'Accounts Balance',
    method: 'GET',
    path: '/account-balance/{id}',
    name: 'AccountsBalanceGetAccountBalanceById',
  },
  {
    tag: 'Accounts Balance',
    method: 'PUT',
    path: '/account-balance/{id}',
    name: 'AccountsBalancePutAccountBalanceById',
  },
  {
    tag: 'Accounts Balance',
    method: 'DELETE',
    path: '/account-balance/{id}',
    name: 'AccountsBalanceDeleteAccountBalanceById',
  },
  {
    tag: 'Accounts Balance',
    method: 'GET',
    path: '/account-balance/account/{accountId}',
    name: 'AccountsBalanceGetAccountBalanceAccountByAccountId',
  },
  {
    tag: 'Accounts Source',
    method: 'POST',
    path: '/account-source',
    name: 'AccountsSourcePostAccountSource',
  },
  {
    tag: 'Accounts Source',
    method: 'GET',
    path: '/account-source',
    name: 'AccountsSourceGetAccountSource',
  },
  {
    tag: 'Accounts Source',
    method: 'GET',
    path: '/account-source/{id}',
    name: 'AccountsSourceGetAccountSourceById',
  },
  {
    tag: 'Accounts Source',
    method: 'PUT',
    path: '/account-source/{id}',
    name: 'AccountsSourcePutAccountSourceById',
  },
  {
    tag: 'Accounts Source',
    method: 'DELETE',
    path: '/account-source/{id}',
    name: 'AccountsSourceDeleteAccountSourceById',
  },
  {
    tag: 'Accounts Source',
    method: 'GET',
    path: '/account-source/account/{accountId}',
    name: 'AccountsSourceGetAccountSourceAccountByAccountId',
  },
  { tag: 'Banks', method: 'POST', path: '/banks', name: 'BanksPostBanks' },
  { tag: 'Banks', method: 'GET', path: '/banks', name: 'BanksGetBanks' },
  {
    tag: 'Banks',
    method: 'GET',
    path: '/banks/{id}',
    name: 'BanksGetBanksById',
  },
  {
    tag: 'Banks',
    method: 'PUT',
    path: '/banks/{id}',
    name: 'BanksPutBanksById',
  },
  {
    tag: 'Banks',
    method: 'DELETE',
    path: '/banks/{id}',
    name: 'BanksDeleteBanksById',
  },
  {
    tag: 'Categories',
    method: 'POST',
    path: '/categories',
    name: 'CategoriesPostCategories',
  },
  {
    tag: 'Categories',
    method: 'GET',
    path: '/categories',
    name: 'CategoriesGetCategories',
  },
  {
    tag: 'Categories',
    method: 'GET',
    path: '/categories/{id}',
    name: 'CategoriesGetCategoriesById',
  },
  {
    tag: 'Categories',
    method: 'PUT',
    path: '/categories/{id}',
    name: 'CategoriesPutCategoriesById',
  },
  {
    tag: 'Categories',
    method: 'DELETE',
    path: '/cateories/{id}',
    name: 'CategoriesDeleteCateoriesById',
  },
  { tag: 'Budget', method: 'POST', path: '/budget', name: 'BudgetPostBudget' },
  { tag: 'Budget', method: 'GET', path: '/budget', name: 'BudgetGetBudget' },
  {
    tag: 'Budget',
    method: 'GET',
    path: '/budget/{id}',
    name: 'BudgetGetBudgetById',
  },
  {
    tag: 'Budget',
    method: 'PUT',
    path: '/budget/{id}',
    name: 'BudgetPutBudgetById',
  },
  {
    tag: 'Budget',
    method: 'DELETE',
    path: '/budget/{id}',
    name: 'BudgetDeleteBudgetById',
  },
  {
    tag: 'Budget',
    method: 'GET',
    path: '/budget/user/{userId}',
    name: 'BudgetGetBudgetUserByUserId',
  },
  {
    tag: 'Credit Cards',
    method: 'POST',
    path: '/credit-cards',
    name: 'CreditCardsPostCreditCards',
  },
  {
    tag: 'Credit Cards',
    method: 'GET',
    path: '/credit-cards',
    name: 'CreditCardsGetCreditCards',
  },
  {
    tag: 'Credit Cards',
    method: 'GET',
    path: '/credit-cards/{id}',
    name: 'CreditCardsGetCreditCardsById',
  },
  {
    tag: 'Credit Cards',
    method: 'PUT',
    path: '/credit-cards/{id}',
    name: 'CreditCardsPutCreditCardsById',
  },
  {
    tag: 'Credit Cards',
    method: 'DELETE',
    path: '/credit-cards/{id}',
    name: 'CreditCardsDeleteCreditCardsById',
  },
  {
    tag: 'Credit Cards',
    method: 'GET',
    path: '/credit-cards/user/{userId}',
    name: 'CreditCardsGetCreditCardsUserByUserId',
  },
  { tag: 'Debts', method: 'POST', path: '/debts', name: 'DebtsPostDebts' },
  { tag: 'Debts', method: 'GET', path: '/debts', name: 'DebtsGetDebts' },
  {
    tag: 'Debts',
    method: 'GET',
    path: '/debts/{id}',
    name: 'DebtsGetDebtsById',
  },
  {
    tag: 'Debts',
    method: 'PUT',
    path: '/debts/{id}',
    name: 'DebtsPutDebtsById',
  },
  {
    tag: 'Debts',
    method: 'DELETE',
    path: '/debts/{id}',
    name: 'DebtsDeleteDebtsById',
  },
  {
    tag: 'Debts',
    method: 'GET',
    path: '/debts/user/{userId}',
    name: 'DebtsGetDebtsUserByUserId',
  },
  {
    tag: 'Debt Payments',
    method: 'POST',
    path: '/debt-payments',
    name: 'DebtPaymentsPostDebtPayments',
  },
  {
    tag: 'Debt Payments',
    method: 'GET',
    path: '/debt-payments',
    name: 'DebtPaymentsGetDebtPayments',
  },
  {
    tag: 'Debt Payments',
    method: 'GET',
    path: '/debt-payments/{id}',
    name: 'DebtPaymentsGetDebtPaymentsById',
  },
  {
    tag: 'Debt Payments',
    method: 'PUT',
    path: '/debt-payments/{id}',
    name: 'DebtPaymentsPutDebtPaymentsById',
  },
  {
    tag: 'Debt Payments',
    method: 'DELETE',
    path: '/debt-payments/{id}',
    name: 'DebtPaymentsDeleteDebtPaymentsById',
  },
  {
    tag: 'Debt Payments',
    method: 'GET',
    path: '/debt-payments/debt/{debtId}',
    name: 'DebtPaymentsGetDebtPaymentsDebtByDebtId',
  },
  {
    tag: 'Expenses',
    method: 'POST',
    path: '/expenses',
    name: 'ExpensesPostExpenses',
  },
  {
    tag: 'Expenses',
    method: 'GET',
    path: '/expenses',
    name: 'ExpensesGetExpenses',
  },
  {
    tag: 'Expenses',
    method: 'GET',
    path: '/expenses/{id}',
    name: 'ExpensesGetExpensesById',
  },
  {
    tag: 'Expenses',
    method: 'PUT',
    path: '/expenses/{id}',
    name: 'ExpensesPutExpensesById',
  },
  {
    tag: 'Expenses',
    method: 'DELETE',
    path: '/expenses/{id}',
    name: 'ExpensesDeleteExpensesById',
  },
  {
    tag: 'Expenses',
    method: 'GET',
    path: '/expenses/user/{userId}',
    name: 'ExpensesGetExpensesUserByUserId',
  },
  {
    tag: 'Expenses',
    method: 'GET',
    path: '/expenses/category/{categoryId}',
    name: 'ExpensesGetExpensesCategoryByCategoryId',
  },
  {
    tag: 'Incomes',
    method: 'POST',
    path: '/income',
    name: 'IncomesPostIncome',
  },
  { tag: 'Incomes', method: 'GET', path: '/income', name: 'IncomesGetIncome' },
  {
    tag: 'Incomes',
    method: 'GET',
    path: '/income/{id}',
    name: 'IncomesGetIncomeById',
  },
  {
    tag: 'Incomes',
    method: 'PUT',
    path: '/income/{id}',
    name: 'IncomesPutIncomeById',
  },
  {
    tag: 'Incomes',
    method: 'DELETE',
    path: '/income/{id}',
    name: 'IncomesDeleteIncomeById',
  },
  {
    tag: 'Incomes',
    method: 'GET',
    path: '/income/user/{userId}',
    name: 'IncomesGetIncomeUserByUserId',
  },
  {
    tag: 'Incomes',
    method: 'GET',
    path: '/income/source/{sourceId}',
    name: 'IncomesGetIncomeSourceBySourceId',
  },
  {
    tag: 'Income Source',
    method: 'POST',
    path: '/income-source',
    name: 'IncomeSourcePostIncomeSource',
  },
  {
    tag: 'Income Source',
    method: 'GET',
    path: '/income-source',
    name: 'IncomeSourceGetIncomeSource',
  },
  {
    tag: 'Income Source',
    method: 'GET',
    path: '/income-source/{id}',
    name: 'IncomeSourceGetIncomeSourceById',
  },
  {
    tag: 'Income Source',
    method: 'PUT',
    path: '/income-source/{id}',
    name: 'IncomeSourcePutIncomeSourceById',
  },
  {
    tag: 'Income Source',
    method: 'DELETE',
    path: '/income-source/{id}',
    name: 'IncomeSourceDeleteIncomeSourceById',
  },
  {
    tag: 'Default',
    method: 'GET',
    path: '/income-sources/user/{userId}',
    name: 'DefaultGetIncomeSourcesUserByUserId',
  },
  {
    tag: 'Investments',
    method: 'POST',
    path: '/investment',
    name: 'InvestmentsPostInvestment',
  },
  {
    tag: 'Investments',
    method: 'GET',
    path: '/investment',
    name: 'InvestmentsGetInvestment',
  },
  {
    tag: 'Investments',
    method: 'GET',
    path: '/investment/user/{userId}',
    name: 'InvestmentsGetInvestmentUserByUserId',
  },
  {
    tag: 'Investments',
    method: 'PUT',
    path: '/investment/{id}',
    name: 'InvestmentsPutInvestmentById',
  },
  {
    tag: 'Investments',
    method: 'DELETE',
    path: '/investment/{id}',
    name: 'InvestmentsDeleteInvestmentById',
  },
  {
    tag: 'Investment Goals',
    method: 'POST',
    path: '/investment-goal',
    name: 'InvestmentGoalsPostInvestmentGoal',
  },
  {
    tag: 'Investment Goals',
    method: 'GET',
    path: '/investment-goal',
    name: 'InvestmentGoalsGetInvestmentGoal',
  },
  {
    tag: 'Investment Goals',
    method: 'PUT',
    path: '/investment-goal/{id}',
    name: 'InvestmentGoalsPutInvestmentGoalById',
  },
  {
    tag: 'Investment Goals',
    method: 'DELETE',
    path: '/investment-goal/{id}',
    name: 'InvestmentGoalsDeleteInvestmentGoalById',
  },
  {
    tag: 'Transaction',
    method: 'POST',
    path: '/transaction',
    name: 'TransactionPostTransaction',
  },
  {
    tag: 'Transaction',
    method: 'GET',
    path: '/transaction',
    name: 'TransactionGetTransaction',
  },
  {
    tag: 'Transaction',
    method: 'GET',
    path: '/transaction/{id}',
    name: 'TransactionGetTransactionById',
  },
  {
    tag: 'Transaction',
    method: 'PUT',
    path: '/transaction/{id}',
    name: 'TransactionPutTransactionById',
  },
  {
    tag: 'Transaction',
    method: 'DELETE',
    path: '/transaction/{id}',
    name: 'TransactionDeleteTransactionById',
  },
  {
    tag: 'Transactions Attachment',
    method: 'POST',
    path: '/transaction-attachment',
    name: 'TransactionsAttachmentPostTransactionAttachment',
  },
  {
    tag: 'Transactions Attachment',
    method: 'GET',
    path: '/transaction-attachment',
    name: 'TransactionsAttachmentGetTransactionAttachment',
  },
  {
    tag: 'Transactions Attachment',
    method: 'GET',
    path: '/transaction-attachment/{id}',
    name: 'TransactionsAttachmentGetTransactionAttachmentById',
  },
  {
    tag: 'Transactions Attachment',
    method: 'PUT',
    path: '/transaction-attachment/{id}',
    name: 'TransactionsAttachmentPutTransactionAttachmentById',
  },
  {
    tag: 'Transactions Attachment',
    method: 'DELETE',
    path: '/transaction-attachment/{id}',
    name: 'TransactionsAttachmentDeleteTransactionAttachmentById',
  },
  {
    tag: 'Reports',
    method: 'GET',
    path: '/reports/dashboard',
    name: 'ReportsGetReportsDashboard',
  },
  {
    tag: 'Reports',
    method: 'GET',
    path: '/reports/evolution',
    name: 'ReportsGetReportsEvolution',
  },
  { tag: 'Health', method: 'GET', path: '/health', name: 'HealthGetHealth' },
]
