export type AuthGetCsrfTokenParams = Record<string, never>
export type AuthGetCsrfTokenQuery = Record<string, never>
export type AuthGetCsrfTokenBody = unknown
export type AuthGetCsrfTokenResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AuthCreateLoginParams = Record<string, never>
export type AuthCreateLoginQuery = Record<string, never>
export type AuthCreateLoginBody = { "email": string; "password": string }
export type AuthCreateLoginResponse = { "success": boolean; "message": string; "data": { "token": string; "user": { "name": string; "surname": string; "email": string; "password": string; "contact": string; "id": string; "createdAt": string; "updatedAt"?: string } } }
export type AuthCreateRefreshTokenParams = Record<string, never>
export type AuthCreateRefreshTokenQuery = Record<string, never>
export type AuthCreateRefreshTokenBody = unknown
export type AuthCreateRefreshTokenResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AuthCreateLogoutParams = Record<string, never>
export type AuthCreateLogoutQuery = Record<string, never>
export type AuthCreateLogoutBody = unknown
export type AuthCreateLogoutResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AuthCreateForgotPasswordParams = Record<string, never>
export type AuthCreateForgotPasswordQuery = Record<string, never>
export type AuthCreateForgotPasswordBody = { "email": string }
export type AuthCreateForgotPasswordResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AuthCreateResetPasswordParams = Record<string, never>
export type AuthCreateResetPasswordQuery = Record<string, never>
export type AuthCreateResetPasswordBody = { "token": string; "newPassword": string; "confirmPassword": string }
export type AuthCreateResetPasswordResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AuthCreateVerifyResetTokenParams = Record<string, never>
export type AuthCreateVerifyResetTokenQuery = Record<string, never>
export type AuthCreateVerifyResetTokenBody = { "token": string }
export type AuthCreateVerifyResetTokenResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AuthGetResetPasswordByTokenParams = { "token": string }
export type AuthGetResetPasswordByTokenQuery = Record<string, never>
export type AuthGetResetPasswordByTokenBody = unknown
export type AuthGetResetPasswordByTokenResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type UsersCreateParams = Record<string, never>
export type UsersCreateQuery = Record<string, never>
export type UsersCreateBody = { "name": string; "surname": string; "email": string; "password": string; "contact": string }
export type UsersCreateResponse = { "success": boolean; "message": string; "data": { "name": string; "surname": string; "email": string; "password": string; "contact": string; "id": string; "createdAt": string; "updatedAt"?: string } }
export type UsersGetParams = Record<string, never>
export type UsersGetQuery = Record<string, never>
export type UsersGetBody = unknown
export type UsersGetResponse = { "success": boolean; "message": string; "data": { "name": string; "surname": string; "email": string; "password": string; "contact": string; "id": string; "createdAt": string; "updatedAt"?: string }[] }
export type UsersGetByIdParams = { "id": string }
export type UsersGetByIdQuery = Record<string, never>
export type UsersGetByIdBody = unknown
export type UsersGetByIdResponse = { "success": boolean; "message": string; "data": { "name": string; "surname": string; "email": string; "password": string; "contact": string; "id": string; "createdAt": string; "updatedAt"?: string } }
export type UsersUpdateByIdParams = { "id": string }
export type UsersUpdateByIdQuery = Record<string, never>
export type UsersUpdateByIdBody = { "name"?: string; "surname"?: string; "email"?: string; "password"?: string; "contact"?: string; "updateAt"?: string }
export type UsersUpdateByIdResponse = { "success": boolean; "message": string; "data": { "name": string; "surname": string; "email": string; "password": string; "contact": string; "id": string; "createdAt": string; "updatedAt"?: string } }
export type UsersDeleteByIdParams = { "id": string }
export type UsersDeleteByIdQuery = Record<string, never>
export type UsersDeleteByIdBody = unknown
export type UsersDeleteByIdResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type UsersGetByIdProfileParams = { "id": string }
export type UsersGetByIdProfileQuery = Record<string, never>
export type UsersGetByIdProfileBody = unknown
export type UsersGetByIdProfileResponse = { "success": boolean; "message": string; "data": { "name": string; "surname": string; "email": string; "password": string; "contact": string; "id": string; "createdAt": string; "updatedAt"?: string } }
export type UsersUpdateByIdProfileParams = { "id": string }
export type UsersUpdateByIdProfileQuery = Record<string, never>
export type UsersUpdateByIdProfileBody = { "name"?: string; "surname"?: string; "contact"?: string }
export type UsersUpdateByIdProfileResponse = { "success": boolean; "message": string; "data": { "id": string; "name": string; "surname": string; "email": string; "contact": string; "role": "ADMIN" | "USER"; "createdAt": string | string; "updatedAt": string | string } }
export type UsersCreateByIdChangePasswordParams = { "id": string }
export type UsersCreateByIdChangePasswordQuery = Record<string, never>
export type UsersCreateByIdChangePasswordBody = { "currentPassword": string; "newPassword": string; "confirmPassword": string }
export type UsersCreateByIdChangePasswordResponse = { "success": boolean; "message": string; "data"?: null }
export type UsersGetByIdSettingsParams = { "id": string }
export type UsersGetByIdSettingsQuery = Record<string, never>
export type UsersGetByIdSettingsBody = unknown
export type UsersGetByIdSettingsResponse = { "success": boolean; "message": string; "data": { "id": string; "userId": string; "language": string; "currency": string; "theme": string; "timezone": string; "dateFormat": string; "twoFactorEnabled": boolean; "createdAt": string | string; "updatedAt": string | string } }
export type UsersUpdateByIdSettingsParams = { "id": string }
export type UsersUpdateByIdSettingsQuery = Record<string, never>
export type UsersUpdateByIdSettingsBody = { "language"?: "pt-BR" | "en-US" | "es-ES"; "currency"?: "MZN" | "USD" | "EUR" | "GBP" | "BRL" | "JPY" | "CNY" | "INR" | "RUB" | "AUD" | "CAD"; "theme"?: "light" | "dark" | "auto"; "timezone"?: string; "dateFormat"?: string; "twoFactorEnabled"?: boolean }
export type UsersUpdateByIdSettingsResponse = { "success": boolean; "message": string; "data": { "id": string; "userId": string; "language": string; "currency": string; "theme": string; "timezone": string; "dateFormat": string; "twoFactorEnabled": boolean; "createdAt": string | string; "updatedAt": string | string } }
export type AccountsCreateParams = Record<string, never>
export type AccountsCreateQuery = Record<string, never>
export type AccountsCreateBody = { "accountName": string; "accountType": "current" | "savings" | "salary" | "digital" | "joint" | "investment"; "accountHolderName": string; "balance"?: number; "userId": string; "bankId"?: string | null; "currency"?: "MZN" | "USD" | "EUR" | "GBP" | "BRL" | "JPY" | "CNY" | "INR" | "RUB" | "AUD" | "CAD"; "isActive"?: boolean; "isDefault"?: boolean; "isJoint"?: boolean }
export type AccountsCreateResponse = { "success": boolean; "message": string; "data": { "accountName": string; "accountType": "current" | "savings" | "salary" | "digital" | "joint" | "investment"; "accountHolderName": string; "balance": number | string | {  }; "userId": string; "bankId"?: string | null; "currency": "MZN" | "USD" | "EUR" | "GBP" | "BRL" | "JPY" | "CNY" | "INR" | "RUB" | "AUD" | "CAD"; "isActive": boolean; "isDefault": boolean; "isJoint": boolean; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type AccountsGetParams = Record<string, never>
export type AccountsGetQuery = Record<string, never>
export type AccountsGetBody = unknown
export type AccountsGetResponse = { "success": boolean; "message": string; "data": { "items": { "accountName": string; "accountType": "current" | "savings" | "salary" | "digital" | "joint" | "investment"; "accountHolderName": string; "balance": number | string | {  }; "userId": string; "bankId"?: string | null; "currency": "MZN" | "USD" | "EUR" | "GBP" | "BRL" | "JPY" | "CNY" | "INR" | "RUB" | "AUD" | "CAD"; "isActive": boolean; "isDefault": boolean; "isJoint": boolean; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[]; "total": number; "page": number; "pageSize": number } }
export type AccountsGetByIdParams = { "id": string }
export type AccountsGetByIdQuery = Record<string, never>
export type AccountsGetByIdBody = unknown
export type AccountsGetByIdResponse = { "success": boolean; "message": string; "data": { "accountName": string; "accountType": "current" | "savings" | "salary" | "digital" | "joint" | "investment"; "accountHolderName": string; "balance": number | string | {  }; "userId": string; "bankId"?: string | null; "currency": "MZN" | "USD" | "EUR" | "GBP" | "BRL" | "JPY" | "CNY" | "INR" | "RUB" | "AUD" | "CAD"; "isActive": boolean; "isDefault": boolean; "isJoint": boolean; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type AccountsUpdateByIdParams = { "id": string }
export type AccountsUpdateByIdQuery = Record<string, never>
export type AccountsUpdateByIdBody = { "accountName"?: string; "accountType"?: "current" | "savings" | "salary" | "digital" | "joint" | "investment"; "accountHolderName"?: string; "balance"?: number; "userId"?: string; "bankId"?: string | null; "currency"?: "MZN" | "USD" | "EUR" | "GBP" | "BRL" | "JPY" | "CNY" | "INR" | "RUB" | "AUD" | "CAD"; "isActive"?: boolean; "isDefault"?: boolean; "isJoint"?: boolean; "updateAt"?: string }
export type AccountsUpdateByIdResponse = { "success": boolean; "message": string; "data": { "accountName": string; "accountType": "current" | "savings" | "salary" | "digital" | "joint" | "investment"; "accountHolderName": string; "balance": number | string | {  }; "userId": string; "bankId"?: string | null; "currency": "MZN" | "USD" | "EUR" | "GBP" | "BRL" | "JPY" | "CNY" | "INR" | "RUB" | "AUD" | "CAD"; "isActive": boolean; "isDefault": boolean; "isJoint": boolean; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type AccountsDeleteByIdParams = { "id": string }
export type AccountsDeleteByIdQuery = Record<string, never>
export type AccountsDeleteByIdBody = unknown
export type AccountsDeleteByIdResponse = { "success": boolean; "message": string; "data"?: null }
export type AccountsGetByIdTransactionsParams = { "id": string }
export type AccountsGetByIdTransactionsQuery = Record<string, never>
export type AccountsGetByIdTransactionsBody = unknown
export type AccountsGetByIdTransactionsResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AccountsGetDefaultByUserParams = { "id": string }
export type AccountsGetDefaultByUserQuery = Record<string, never>
export type AccountsGetDefaultByUserBody = unknown
export type AccountsGetDefaultByUserResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AccountsGetAccountByUserParams = { "userId": string }
export type AccountsGetAccountByUserQuery = Record<string, never>
export type AccountsGetAccountByUserBody = unknown
export type AccountsGetAccountByUserResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AccountsBalanceCreateAccountBalanceParams = Record<string, never>
export type AccountsBalanceCreateAccountBalanceQuery = Record<string, never>
export type AccountsBalanceCreateAccountBalanceBody = { "accountId": string; "date": string; "balance": number }
export type AccountsBalanceCreateAccountBalanceResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AccountsBalanceGetAccountBalanceParams = Record<string, never>
export type AccountsBalanceGetAccountBalanceQuery = Record<string, never>
export type AccountsBalanceGetAccountBalanceBody = unknown
export type AccountsBalanceGetAccountBalanceResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AccountsBalanceGetAccountBalanceByIdParams = { "id": string }
export type AccountsBalanceGetAccountBalanceByIdQuery = Record<string, never>
export type AccountsBalanceGetAccountBalanceByIdBody = unknown
export type AccountsBalanceGetAccountBalanceByIdResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AccountsBalanceUpdateAccountBalanceByIdParams = { "id": string }
export type AccountsBalanceUpdateAccountBalanceByIdQuery = Record<string, never>
export type AccountsBalanceUpdateAccountBalanceByIdBody = { "accountId"?: string; "date"?: string; "balance"?: number }
export type AccountsBalanceUpdateAccountBalanceByIdResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AccountsBalanceDeleteAccountBalanceByIdParams = { "id": string }
export type AccountsBalanceDeleteAccountBalanceByIdQuery = Record<string, never>
export type AccountsBalanceDeleteAccountBalanceByIdBody = unknown
export type AccountsBalanceDeleteAccountBalanceByIdResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AccountsBalanceGetAccountBalanceByAccountParams = { "accountId": string }
export type AccountsBalanceGetAccountBalanceByAccountQuery = Record<string, never>
export type AccountsBalanceGetAccountBalanceByAccountBody = unknown
export type AccountsBalanceGetAccountBalanceByAccountResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AccountsSourceCreateAccountSourceParams = Record<string, never>
export type AccountsSourceCreateAccountSourceQuery = Record<string, never>
export type AccountsSourceCreateAccountSourceBody = { "accountId": string; "source": string }
export type AccountsSourceCreateAccountSourceResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AccountsSourceGetAccountSourceParams = Record<string, never>
export type AccountsSourceGetAccountSourceQuery = Record<string, never>
export type AccountsSourceGetAccountSourceBody = unknown
export type AccountsSourceGetAccountSourceResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AccountsSourceGetAccountSourceByIdParams = { "id": string }
export type AccountsSourceGetAccountSourceByIdQuery = Record<string, never>
export type AccountsSourceGetAccountSourceByIdBody = unknown
export type AccountsSourceGetAccountSourceByIdResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AccountsSourceUpdateAccountSourceByIdParams = { "id": string }
export type AccountsSourceUpdateAccountSourceByIdQuery = Record<string, never>
export type AccountsSourceUpdateAccountSourceByIdBody = { "accountId"?: string; "source"?: string }
export type AccountsSourceUpdateAccountSourceByIdResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AccountsSourceDeleteAccountSourceByIdParams = { "id": string }
export type AccountsSourceDeleteAccountSourceByIdQuery = Record<string, never>
export type AccountsSourceDeleteAccountSourceByIdBody = unknown
export type AccountsSourceDeleteAccountSourceByIdResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type AccountsSourceGetAccountSourceByAccountParams = { "accountId": string }
export type AccountsSourceGetAccountSourceByAccountQuery = Record<string, never>
export type AccountsSourceGetAccountSourceByAccountBody = unknown
export type AccountsSourceGetAccountSourceByAccountResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type BanksCreateParams = Record<string, never>
export type BanksCreateQuery = Record<string, never>
export type BanksCreateBody = { "bankName": string; "logoUrl"?: string | null }
export type BanksCreateResponse = { "success": boolean; "message": string; "data": { "bankName": string; "logoUrl"?: string | null; "id"?: string } }
export type BanksGetParams = Record<string, never>
export type BanksGetQuery = Record<string, never>
export type BanksGetBody = unknown
export type BanksGetResponse = { "success": boolean; "message": string; "data": { "bankName": string; "logoUrl"?: string | null; "id"?: string }[] }
export type BanksGetByIdParams = { "id": string }
export type BanksGetByIdQuery = Record<string, never>
export type BanksGetByIdBody = unknown
export type BanksGetByIdResponse = { "success": boolean; "message": string; "data": { "bankName": string; "logoUrl"?: string | null; "id"?: string } }
export type BanksUpdateByIdParams = { "id": string }
export type BanksUpdateByIdQuery = Record<string, never>
export type BanksUpdateByIdBody = { "bankName"?: string; "logoUrl"?: string | null }
export type BanksUpdateByIdResponse = { "success": boolean; "message": string; "data": { "bankName": string; "logoUrl"?: string | null; "id"?: string } }
export type BanksDeleteByIdParams = { "id": string }
export type BanksDeleteByIdQuery = Record<string, never>
export type BanksDeleteByIdBody = unknown
export type BanksDeleteByIdResponse = { "success": boolean; "message": string; "data"?: null }
export type CategoriesCreateParams = Record<string, never>
export type CategoriesCreateQuery = Record<string, never>
export type CategoriesCreateBody = { "categoryName": string; "categoryType": "income" | "expense" | "transfer" | "investment" | "creditCardExpense" | "debtPayment" | "debtIncome" | "budgetExpense" | "budgetIncome" | "creditCardPayment" | "creditCardTransfer" | "creditCardIncome"; "icon"?: string | null; "color"?: string | null }
export type CategoriesCreateResponse = { "success": boolean; "message": string; "data": { "categoryName": string; "categoryType": "income" | "expense" | "transfer" | "investment" | "creditCardExpense" | "debtPayment" | "debtIncome" | "budgetExpense" | "budgetIncome" | "creditCardPayment" | "creditCardTransfer" | "creditCardIncome"; "icon"?: string | null; "color"?: string | null; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type CategoriesGetParams = Record<string, never>
export type CategoriesGetQuery = Record<string, never>
export type CategoriesGetBody = unknown
export type CategoriesGetResponse = { "success": boolean; "message": string; "data": { "categoryName": string; "categoryType": "income" | "expense" | "transfer" | "investment" | "creditCardExpense" | "debtPayment" | "debtIncome" | "budgetExpense" | "budgetIncome" | "creditCardPayment" | "creditCardTransfer" | "creditCardIncome"; "icon"?: string | null; "color"?: string | null; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[] }
export type CategoriesGetByIdParams = { "id": string }
export type CategoriesGetByIdQuery = Record<string, never>
export type CategoriesGetByIdBody = unknown
export type CategoriesGetByIdResponse = { "success": boolean; "message": string; "data": { "categoryName": string; "categoryType": "income" | "expense" | "transfer" | "investment" | "creditCardExpense" | "debtPayment" | "debtIncome" | "budgetExpense" | "budgetIncome" | "creditCardPayment" | "creditCardTransfer" | "creditCardIncome"; "icon"?: string | null; "color"?: string | null; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type CategoriesUpdateByIdParams = { "id": string }
export type CategoriesUpdateByIdQuery = Record<string, never>
export type CategoriesUpdateByIdBody = { "categoryName"?: string; "categoryType"?: "income" | "expense" | "transfer" | "investment" | "creditCardExpense" | "debtPayment" | "debtIncome" | "budgetExpense" | "budgetIncome" | "creditCardPayment" | "creditCardTransfer" | "creditCardIncome"; "icon"?: string | null; "color"?: string | null }
export type CategoriesUpdateByIdResponse = { "success": boolean; "message": string; "data": { "categoryName": string; "categoryType": "income" | "expense" | "transfer" | "investment" | "creditCardExpense" | "debtPayment" | "debtIncome" | "budgetExpense" | "budgetIncome" | "creditCardPayment" | "creditCardTransfer" | "creditCardIncome"; "icon"?: string | null; "color"?: string | null; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type CategoriesDeleteCateoriesByIdParams = { "id": string }
export type CategoriesDeleteCateoriesByIdQuery = Record<string, never>
export type CategoriesDeleteCateoriesByIdBody = unknown
export type CategoriesDeleteCateoriesByIdResponse = { "success": boolean; "message": string; "data"?: null }
export type BudgetCreateParams = Record<string, never>
export type BudgetCreateQuery = Record<string, never>
export type BudgetCreateBody = { "userId": string; "categoryId": string; "month": number; "year": number; "limit": number }
export type BudgetCreateResponse = { "success": boolean; "message": string; "data": { "userId": string; "categoryId": string; "month": number; "year": number; "limit": number | string | {  }; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type BudgetGetParams = Record<string, never>
export type BudgetGetQuery = Record<string, never>
export type BudgetGetBody = unknown
export type BudgetGetResponse = { "success": boolean; "message": string; "data": { "userId": string; "categoryId": string; "month": number; "year": number; "limit": number | string | {  }; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[] }
export type BudgetGetByIdParams = { "id": string }
export type BudgetGetByIdQuery = Record<string, never>
export type BudgetGetByIdBody = unknown
export type BudgetGetByIdResponse = { "success": boolean; "message": string; "data": { "userId": string; "categoryId": string; "month": number; "year": number; "limit": number | string | {  }; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type BudgetUpdateByIdParams = { "id": string }
export type BudgetUpdateByIdQuery = Record<string, never>
export type BudgetUpdateByIdBody = { "userId"?: string; "categoryId"?: string; "month"?: number; "year"?: number; "limit"?: number }
export type BudgetUpdateByIdResponse = { "success": boolean; "message": string; "data": { "userId": string; "categoryId": string; "month": number; "year": number; "limit": number | string | {  }; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type BudgetDeleteByIdParams = { "id": string }
export type BudgetDeleteByIdQuery = Record<string, never>
export type BudgetDeleteByIdBody = unknown
export type BudgetDeleteByIdResponse = { "success": boolean; "message": string; "data"?: null }
export type BudgetGetByUserParams = { "userId": string }
export type BudgetGetByUserQuery = Record<string, never>
export type BudgetGetByUserBody = unknown
export type BudgetGetByUserResponse = { "success": boolean; "message": string; "data": { "userId": string; "categoryId": string; "month": number; "year": number; "limit": number | string | {  }; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[] }
export type BudgetCreateGenerateRecurringParams = Record<string, never>
export type BudgetCreateGenerateRecurringQuery = { "userId": string; "month": string; "year": string }
export type BudgetCreateGenerateRecurringBody = unknown
export type BudgetCreateGenerateRecurringResponse = unknown
export type CreditCardsCreateParams = Record<string, never>
export type CreditCardsCreateQuery = Record<string, never>
export type CreditCardsCreateBody = { "name": string; "limit": number; "dueDay": number; "userId": string }
export type CreditCardsCreateResponse = { "success": boolean; "message": string; "data": { "name": string; "limit": number | string | {  }; "dueDay": number; "userId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type CreditCardsGetParams = Record<string, never>
export type CreditCardsGetQuery = Record<string, never>
export type CreditCardsGetBody = unknown
export type CreditCardsGetResponse = { "success": boolean; "message": string; "data": { "name": string; "limit": number | string | {  }; "dueDay": number; "userId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[] }
export type CreditCardsGetByIdParams = { "id": string }
export type CreditCardsGetByIdQuery = Record<string, never>
export type CreditCardsGetByIdBody = unknown
export type CreditCardsGetByIdResponse = { "success": boolean; "message": string; "data": { "name": string; "limit": number | string | {  }; "dueDay": number; "userId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type CreditCardsUpdateByIdParams = { "id": string }
export type CreditCardsUpdateByIdQuery = Record<string, never>
export type CreditCardsUpdateByIdBody = { "name"?: string; "limit"?: number; "dueDay"?: number; "userId"?: string }
export type CreditCardsUpdateByIdResponse = { "success": boolean; "message": string; "data": { "name": string; "limit": number | string | {  }; "dueDay": number; "userId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type CreditCardsDeleteByIdParams = { "id": string }
export type CreditCardsDeleteByIdQuery = Record<string, never>
export type CreditCardsDeleteByIdBody = unknown
export type CreditCardsDeleteByIdResponse = { "success": boolean; "message": string; "data"?: null }
export type CreditCardsGetByUserParams = { "userId": string }
export type CreditCardsGetByUserQuery = Record<string, never>
export type CreditCardsGetByUserBody = unknown
export type CreditCardsGetByUserResponse = { "success": boolean; "message": string; "data": { "name": string; "limit": number | string | {  }; "dueDay": number; "userId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[] }
export type CreditCardExpensesCreateParams = Record<string, never>
export type CreditCardExpensesCreateQuery = Record<string, never>
export type CreditCardExpensesCreateBody = { "description": string; "amount": number; "date": string; "categoryId": string; "creditCardId": string }
export type CreditCardExpensesCreateResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "date": string; "categoryId": string; "creditCardId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type CreditCardExpensesGetParams = Record<string, never>
export type CreditCardExpensesGetQuery = Record<string, never>
export type CreditCardExpensesGetBody = unknown
export type CreditCardExpensesGetResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "date": string; "categoryId": string; "creditCardId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[] }
export type CreditCardExpensesGetByIdParams = { "id": string }
export type CreditCardExpensesGetByIdQuery = Record<string, never>
export type CreditCardExpensesGetByIdBody = unknown
export type CreditCardExpensesGetByIdResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "date": string; "categoryId": string; "creditCardId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type CreditCardExpensesUpdateByIdParams = { "id": string }
export type CreditCardExpensesUpdateByIdQuery = Record<string, never>
export type CreditCardExpensesUpdateByIdBody = { "description"?: string; "amount"?: number; "date"?: string; "categoryId"?: string; "creditCardId"?: string }
export type CreditCardExpensesUpdateByIdResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "date": string; "categoryId": string; "creditCardId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type CreditCardExpensesDeleteByIdParams = { "id": string }
export type CreditCardExpensesDeleteByIdQuery = Record<string, never>
export type CreditCardExpensesDeleteByIdBody = unknown
export type CreditCardExpensesDeleteByIdResponse = { "success": boolean; "message": string; "data"?: null }
export type CreditCardExpensesGetByCreditCardParams = { "creditCardId": string }
export type CreditCardExpensesGetByCreditCardQuery = Record<string, never>
export type CreditCardExpensesGetByCreditCardBody = unknown
export type CreditCardExpensesGetByCreditCardResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "date": string; "categoryId": string; "creditCardId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[] }
export type CreditCardExpensesGetByCategoryParams = { "categoryId": string }
export type CreditCardExpensesGetByCategoryQuery = Record<string, never>
export type CreditCardExpensesGetByCategoryBody = unknown
export type CreditCardExpensesGetByCategoryResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "date": string; "categoryId": string; "creditCardId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[] }
export type DebtsCreateParams = Record<string, never>
export type DebtsCreateQuery = Record<string, never>
export type DebtsCreateBody = { "description": string; "amount": number; "creditor": string; "dueDate": string; "status": "PENDING" | "PAID"; "notes"?: string | null; "paymentDate"?: string | null; "userId": string }
export type DebtsCreateResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string; "creditor": string; "dueDate": string; "status": "PENDING" | "PAID"; "notes"?: string | null; "paymentDate"?: string | null; "userId": string; "id"?: string; "createdAt"?: string } }
export type DebtsGetParams = Record<string, never>
export type DebtsGetQuery = { "page"?: number; "pageSize"?: number; "userId"?: string; "status"?: "PENDING" | "PAID"; "dateFrom"?: string; "dateTo"?: string }
export type DebtsGetBody = unknown
export type DebtsGetResponse = { "success": boolean; "message": string; "data": { "items": { "description": string; "amount": number | string; "creditor": string; "dueDate": string; "status": "PENDING" | "PAID"; "notes"?: string | null; "paymentDate"?: string | null; "userId": string; "id"?: string; "createdAt"?: string }[]; "total": number; "page": number; "pageSize": number } }
export type DebtsGetByIdParams = { "id": string }
export type DebtsGetByIdQuery = Record<string, never>
export type DebtsGetByIdBody = unknown
export type DebtsGetByIdResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string; "creditor": string; "dueDate": string; "status": "PENDING" | "PAID"; "notes"?: string | null; "paymentDate"?: string | null; "userId": string; "id"?: string; "createdAt"?: string } }
export type DebtsUpdateByIdParams = { "id": string }
export type DebtsUpdateByIdQuery = Record<string, never>
export type DebtsUpdateByIdBody = { "description"?: string; "amount"?: number; "creditor"?: string; "dueDate"?: string; "status"?: "PENDING" | "PAID"; "notes"?: string | null; "paymentDate"?: string | null; "userId"?: string }
export type DebtsUpdateByIdResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string; "creditor": string; "dueDate": string; "status": "PENDING" | "PAID"; "notes"?: string | null; "paymentDate"?: string | null; "userId": string; "id"?: string; "createdAt"?: string } }
export type DebtsDeleteByIdParams = { "id": string }
export type DebtsDeleteByIdQuery = Record<string, never>
export type DebtsDeleteByIdBody = unknown
export type DebtsDeleteByIdResponse = { "success": boolean; "message": string }
export type DebtsGetByUserParams = { "userId": string }
export type DebtsGetByUserQuery = Record<string, never>
export type DebtsGetByUserBody = unknown
export type DebtsGetByUserResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string; "creditor": string; "dueDate": string; "status": "PENDING" | "PAID"; "notes"?: string | null; "paymentDate"?: string | null; "userId": string; "id"?: string; "createdAt"?: string }[] }
export type DebtPaymentsCreateParams = Record<string, never>
export type DebtPaymentsCreateQuery = Record<string, never>
export type DebtPaymentsCreateBody = { "amount": number; "date": string; "debtId": string; "accountId"?: string | null; "userId": string; "notes"?: string | null }
export type DebtPaymentsCreateResponse = { "success": boolean; "message": string; "data": { "amount": number | string | {  }; "date": string; "debtId": string; "accountId"?: string | null; "userId": string; "notes"?: string | null; "id"?: string; "createdAt"?: string } }
export type DebtPaymentsGetParams = Record<string, never>
export type DebtPaymentsGetQuery = Record<string, never>
export type DebtPaymentsGetBody = unknown
export type DebtPaymentsGetResponse = { "success": boolean; "message": string; "data": { "amount": number | string | {  }; "date": string; "debtId": string; "accountId"?: string | null; "userId": string; "notes"?: string | null; "id"?: string; "createdAt"?: string }[] }
export type DebtPaymentsGetByIdParams = { "id": string }
export type DebtPaymentsGetByIdQuery = Record<string, never>
export type DebtPaymentsGetByIdBody = unknown
export type DebtPaymentsGetByIdResponse = { "success": boolean; "message": string; "data": { "amount": number | string | {  }; "date": string; "debtId": string; "accountId"?: string | null; "userId": string; "notes"?: string | null; "id"?: string; "createdAt"?: string } }
export type DebtPaymentsUpdateByIdParams = { "id": string }
export type DebtPaymentsUpdateByIdQuery = Record<string, never>
export type DebtPaymentsUpdateByIdBody = { "amount"?: number; "date"?: string; "debtId"?: string; "accountId"?: string | null; "userId"?: string; "notes"?: string | null }
export type DebtPaymentsUpdateByIdResponse = { "success": boolean; "message": string; "data": { "amount": number | string | {  }; "date": string; "debtId": string; "accountId"?: string | null; "userId": string; "notes"?: string | null; "id"?: string; "createdAt"?: string } }
export type DebtPaymentsDeleteByIdParams = { "id": string }
export type DebtPaymentsDeleteByIdQuery = Record<string, never>
export type DebtPaymentsDeleteByIdBody = unknown
export type DebtPaymentsDeleteByIdResponse = { "success": boolean; "message": string; "data"?: null }
export type DebtPaymentsGetDebtByIdParams = { "debtId": string }
export type DebtPaymentsGetDebtByIdQuery = Record<string, never>
export type DebtPaymentsGetDebtByIdBody = unknown
export type DebtPaymentsGetDebtByIdResponse = { "success": boolean; "message": string; "data": { "amount": number | string | {  }; "date": string; "debtId": string; "accountId"?: string | null; "userId": string; "notes"?: string | null; "id"?: string; "createdAt"?: string }[] }
export type ExpensesCreateParams = Record<string, never>
export type ExpensesCreateQuery = Record<string, never>
export type ExpensesCreateBody = { "description": string; "amount": number; "date": string; "month": number; "year": number; "categoryId": string; "accountId": string; "userId": string }
export type ExpensesCreateResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string; "date": string; "month": number; "year": number; "categoryId": string; "accountId": string; "userId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type ExpensesGetParams = Record<string, never>
export type ExpensesGetQuery = { "page"?: number; "pageSize"?: number; "userId"?: string; "categoryId"?: string; "dateFrom"?: string; "dateTo"?: string }
export type ExpensesGetBody = unknown
export type ExpensesGetResponse = { "success": boolean; "message": string; "data": { "items": { "description": string; "amount": number | string; "date": string; "month": number; "year": number; "categoryId": string; "accountId": string; "userId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[]; "total": number; "page": number; "pageSize": number } }
export type ExpensesGetByIdParams = { "id": string }
export type ExpensesGetByIdQuery = Record<string, never>
export type ExpensesGetByIdBody = unknown
export type ExpensesGetByIdResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string; "date": string; "month": number; "year": number; "categoryId": string; "accountId": string; "userId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type ExpensesUpdateByIdParams = { "id": string }
export type ExpensesUpdateByIdQuery = Record<string, never>
export type ExpensesUpdateByIdBody = { "description"?: string; "amount"?: number; "date"?: string; "month"?: number; "year"?: number; "categoryId"?: string; "accountId"?: string; "userId"?: string }
export type ExpensesUpdateByIdResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string; "date": string; "month": number; "year": number; "categoryId": string; "accountId": string; "userId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type ExpensesDeleteByIdParams = { "id": string }
export type ExpensesDeleteByIdQuery = Record<string, never>
export type ExpensesDeleteByIdBody = unknown
export type ExpensesDeleteByIdResponse = { "success": boolean; "message": string; "data"?: null }
export type ExpensesGetByUserParams = { "userId": string }
export type ExpensesGetByUserQuery = Record<string, never>
export type ExpensesGetByUserBody = unknown
export type ExpensesGetByUserResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string; "date": string; "month": number; "year": number; "categoryId": string; "accountId": string; "userId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[] }
export type ExpensesGetByCategoryParams = { "categoryId": string }
export type ExpensesGetByCategoryQuery = Record<string, never>
export type ExpensesGetByCategoryBody = unknown
export type ExpensesGetByCategoryResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string; "date": string; "month": number; "year": number; "categoryId": string; "accountId": string; "userId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[] }
export type IncomesCreateIncomeParams = Record<string, never>
export type IncomesCreateIncomeQuery = Record<string, never>
export type IncomesCreateIncomeBody = { "description": string; "amount": number; "sourceId": string; "accountId"?: string; "date": string; "userId": string }
export type IncomesCreateIncomeResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "sourceId": string; "accountId"?: string; "date": string; "userId": string; "id"?: string; "createdAt"?: string } }
export type IncomesGetIncomeParams = Record<string, never>
export type IncomesGetIncomeQuery = Record<string, never>
export type IncomesGetIncomeBody = unknown
export type IncomesGetIncomeResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "sourceId": string; "accountId"?: string; "date": string; "userId": string; "id"?: string; "createdAt"?: string }[] }
export type IncomesGetIncomeByIdParams = { "id": string }
export type IncomesGetIncomeByIdQuery = Record<string, never>
export type IncomesGetIncomeByIdBody = unknown
export type IncomesGetIncomeByIdResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "sourceId": string; "accountId"?: string; "date": string; "userId": string; "id"?: string; "createdAt"?: string } }
export type IncomesUpdateIncomeByIdParams = { "id": string }
export type IncomesUpdateIncomeByIdQuery = Record<string, never>
export type IncomesUpdateIncomeByIdBody = { "description"?: string; "amount"?: number; "sourceId"?: string; "accountId"?: string; "date"?: string; "userId"?: string }
export type IncomesUpdateIncomeByIdResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "sourceId": string; "accountId"?: string; "date": string; "userId": string; "id"?: string; "createdAt"?: string } }
export type IncomesDeleteIncomeByIdParams = { "id": string }
export type IncomesDeleteIncomeByIdQuery = Record<string, never>
export type IncomesDeleteIncomeByIdBody = unknown
export type IncomesDeleteIncomeByIdResponse = { "success": boolean; "message": string; "data"?: null }
export type IncomesGetIncomeByUserParams = { "userId": string }
export type IncomesGetIncomeByUserQuery = Record<string, never>
export type IncomesGetIncomeByUserBody = unknown
export type IncomesGetIncomeByUserResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "sourceId": string; "accountId"?: string; "date": string; "userId": string; "id"?: string; "createdAt"?: string }[] }
export type IncomesGetIncomeSourceByIdParams = { "sourceId": string }
export type IncomesGetIncomeSourceByIdQuery = Record<string, never>
export type IncomesGetIncomeSourceByIdBody = unknown
export type IncomesGetIncomeSourceByIdResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "sourceId": string; "accountId"?: string; "date": string; "userId": string; "id"?: string; "createdAt"?: string }[] }
export type IncomeSourceCreateParams = Record<string, never>
export type IncomeSourceCreateQuery = Record<string, never>
export type IncomeSourceCreateBody = { "name": string; "frequency": string; "startDate": string; "endDate"?: string | null; "isActive"?: boolean; "userId": string }
export type IncomeSourceCreateResponse = { "success": boolean; "message": string; "data": { "name": string; "frequency": string; "startDate": string; "endDate"?: string | null; "isActive": boolean; "userId": string; "id"?: string; "createdAt"?: string } }
export type IncomeSourceGetParams = Record<string, never>
export type IncomeSourceGetQuery = Record<string, never>
export type IncomeSourceGetBody = unknown
export type IncomeSourceGetResponse = { "success": boolean; "message": string; "data": { "name": string; "frequency": string; "startDate": string; "endDate"?: string | null; "isActive": boolean; "userId": string; "id"?: string; "createdAt"?: string }[] }
export type IncomeSourceGetByIdParams = { "id": string }
export type IncomeSourceGetByIdQuery = Record<string, never>
export type IncomeSourceGetByIdBody = unknown
export type IncomeSourceGetByIdResponse = { "success": boolean; "message": string; "data": { "name": string; "frequency": string; "startDate": string; "endDate"?: string | null; "isActive": boolean; "userId": string; "id"?: string; "createdAt"?: string } }
export type IncomeSourceUpdateByIdParams = { "id": string }
export type IncomeSourceUpdateByIdQuery = Record<string, never>
export type IncomeSourceUpdateByIdBody = { "name"?: string; "frequency"?: string; "startDate"?: string; "endDate"?: string | null; "isActive"?: boolean; "userId"?: string }
export type IncomeSourceUpdateByIdResponse = { "success": boolean; "message": string; "data": { "name": string; "frequency": string; "startDate": string; "endDate"?: string | null; "isActive": boolean; "userId": string; "id"?: string; "createdAt"?: string } }
export type IncomeSourceDeleteByIdParams = { "id": string }
export type IncomeSourceDeleteByIdQuery = Record<string, never>
export type IncomeSourceDeleteByIdBody = unknown
export type IncomeSourceDeleteByIdResponse = { "success": boolean; "message": string; "data"?: null }
export type IncomeSourceGetIncomeSourcesByUserParams = { "userId": string }
export type IncomeSourceGetIncomeSourcesByUserQuery = Record<string, never>
export type IncomeSourceGetIncomeSourcesByUserBody = unknown
export type IncomeSourceGetIncomeSourcesByUserResponse = { "success": boolean; "message": string; "data": { "name": string; "frequency": string; "startDate": string; "endDate"?: string | null; "isActive": boolean; "userId": string; "id"?: string; "createdAt"?: string }[] }
export type InvestmentsCreateInvestmentParams = Record<string, never>
export type InvestmentsCreateInvestmentQuery = Record<string, never>
export type InvestmentsCreateInvestmentBody = { "investimentName": string; "amount": number; "investmentTypeId": string; "investmentGoalId"?: string | null; "notes"?: string | null; "userId": string }
export type InvestmentsCreateInvestmentResponse = { "success": boolean; "message": string; "data": { "investimentName": string; "amount": number | string | {  }; "investmentTypeId": string; "investmentGoalId"?: string | null; "notes"?: string | null; "userId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type InvestmentsGetInvestmentParams = Record<string, never>
export type InvestmentsGetInvestmentQuery = Record<string, never>
export type InvestmentsGetInvestmentBody = unknown
export type InvestmentsGetInvestmentResponse = { "success": boolean; "message": string; "data": { "investimentName": string; "amount": number | string | {  }; "investmentTypeId": string; "investmentGoalId"?: string | null; "notes"?: string | null; "userId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[] }
export type InvestmentsGetInvestmentByUserParams = { "userId": string }
export type InvestmentsGetInvestmentByUserQuery = Record<string, never>
export type InvestmentsGetInvestmentByUserBody = unknown
export type InvestmentsGetInvestmentByUserResponse = { "success": boolean; "message": string; "data": { "investimentName": string; "amount": number | string | {  }; "investmentTypeId": string; "investmentGoalId"?: string | null; "notes"?: string | null; "userId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[] }
export type InvestmentsUpdateInvestmentByIdParams = { "id": string }
export type InvestmentsUpdateInvestmentByIdQuery = Record<string, never>
export type InvestmentsUpdateInvestmentByIdBody = { "investimentName"?: string; "amount"?: number; "investmentTypeId"?: string; "investmentGoalId"?: string | null; "notes"?: string | null; "userId"?: string }
export type InvestmentsUpdateInvestmentByIdResponse = { "success": boolean; "message": string; "data": { "investimentName": string; "amount": number | string | {  }; "investmentTypeId": string; "investmentGoalId"?: string | null; "notes"?: string | null; "userId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type InvestmentsDeleteInvestmentByIdParams = { "id": string }
export type InvestmentsDeleteInvestmentByIdQuery = Record<string, never>
export type InvestmentsDeleteInvestmentByIdBody = unknown
export type InvestmentsDeleteInvestmentByIdResponse = { "success": boolean; "message": string; "data"?: null }
export type InvestmentGoalsCreateInvestmentGoalParams = Record<string, never>
export type InvestmentGoalsCreateInvestmentGoalQuery = Record<string, never>
export type InvestmentGoalsCreateInvestmentGoalBody = { "name": string; "targetAmount": number; "currentAmount"?: number; "targetDate": string; "investmentId": string }
export type InvestmentGoalsCreateInvestmentGoalResponse = { "success": boolean; "message": string; "data": { "name": string; "targetAmount": number | string | {  }; "currentAmount": number | string | {  }; "targetDate": string; "investmentId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type InvestmentGoalsGetInvestmentGoalParams = Record<string, never>
export type InvestmentGoalsGetInvestmentGoalQuery = Record<string, never>
export type InvestmentGoalsGetInvestmentGoalBody = unknown
export type InvestmentGoalsGetInvestmentGoalResponse = { "success": boolean; "message": string; "data": { "name": string; "targetAmount": number | string | {  }; "currentAmount": number | string | {  }; "targetDate": string; "investmentId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[] }
export type InvestmentGoalsUpdateInvestmentGoalByIdParams = { "id": string }
export type InvestmentGoalsUpdateInvestmentGoalByIdQuery = Record<string, never>
export type InvestmentGoalsUpdateInvestmentGoalByIdBody = { "name"?: string; "targetAmount"?: number; "currentAmount"?: number; "targetDate"?: string; "investmentId"?: string }
export type InvestmentGoalsUpdateInvestmentGoalByIdResponse = { "success": boolean; "message": string; "data": { "name": string; "targetAmount": number | string | {  }; "currentAmount": number | string | {  }; "targetDate": string; "investmentId": string; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type InvestmentGoalsDeleteInvestmentGoalByIdParams = { "id": string }
export type InvestmentGoalsDeleteInvestmentGoalByIdQuery = Record<string, never>
export type InvestmentGoalsDeleteInvestmentGoalByIdBody = unknown
export type InvestmentGoalsDeleteInvestmentGoalByIdResponse = { "success": boolean; "message": string; "data"?: null }
export type TransactionCreateParams = Record<string, never>
export type TransactionCreateQuery = Record<string, never>
export type TransactionCreateBody = { "description": string; "amount": number; "type": "income" | "expense" | "transfer" | "investment" | "creditCardExpense" | "debtPayment" | "debtIncome" | "budgetExpense" | "budgetIncome" | "creditCardPayment" | "creditCardTransfer" | "creditCardIncome"; "date": string; "month": number; "year": number; "userId": string; "accountId": string; "debitAccountId"?: string | null; "categoryId": string; "incomeSourceId"?: string | null; "incomeId"?: string | null }
export type TransactionCreateResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "type": "income" | "expense" | "transfer" | "investment" | "creditCardExpense" | "debtPayment" | "debtIncome" | "budgetExpense" | "budgetIncome" | "creditCardPayment" | "creditCardTransfer" | "creditCardIncome"; "date": string; "month": number; "year": number; "userId": string; "accountId": string; "debitAccountId"?: string | null; "categoryId": string; "incomeSourceId"?: string | null; "incomeId"?: string | null; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type TransactionGetTransactionsParams = Record<string, never>
export type TransactionGetTransactionsQuery = { "page"?: number; "pageSize"?: number; "userId"?: string; "accountId"?: string; "categoryId"?: string; "type"?: "income" | "expense" | "transfer" | "investment" | "creditCardExpense" | "debtPayment" | "debtIncome" | "budgetExpense" | "budgetIncome" | "creditCardPayment" | "creditCardTransfer" | "creditCardIncome"; "dateFrom"?: string; "dateTo"?: string }
export type TransactionGetTransactionsBody = unknown
export type TransactionGetTransactionsResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "type": "income" | "expense" | "transfer" | "investment" | "creditCardExpense" | "debtPayment" | "debtIncome" | "budgetExpense" | "budgetIncome" | "creditCardPayment" | "creditCardTransfer" | "creditCardIncome"; "date": string; "month": number; "year": number; "userId": string; "accountId": string; "debitAccountId"?: string | null; "categoryId": string; "incomeSourceId"?: string | null; "incomeId"?: string | null; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[] }
export type TransactionsGetTransactionByIdParams = { "id": string }
export type TransactionsGetTransactionByIdQuery = Record<string, never>
export type TransactionsGetTransactionByIdBody = unknown
export type TransactionsGetTransactionByIdResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "type": "income" | "expense" | "transfer" | "investment" | "creditCardExpense" | "debtPayment" | "debtIncome" | "budgetExpense" | "budgetIncome" | "creditCardPayment" | "creditCardTransfer" | "creditCardIncome"; "date": string; "month": number; "year": number; "userId": string; "accountId": string; "debitAccountId"?: string | null; "categoryId": string; "incomeSourceId"?: string | null; "incomeId"?: string | null; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type TransactionUpdateByIdParams = { "id": string }
export type TransactionUpdateByIdQuery = Record<string, never>
export type TransactionUpdateByIdBody = { "description"?: string; "amount"?: number; "type"?: "income" | "expense" | "transfer" | "investment" | "creditCardExpense" | "debtPayment" | "debtIncome" | "budgetExpense" | "budgetIncome" | "creditCardPayment" | "creditCardTransfer" | "creditCardIncome"; "date"?: string; "month"?: number; "year"?: number; "userId"?: string; "accountId"?: string; "debitAccountId"?: string | null; "categoryId"?: string; "incomeSourceId"?: string | null; "incomeId"?: string | null }
export type TransactionUpdateByIdResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "type": "income" | "expense" | "transfer" | "investment" | "creditCardExpense" | "debtPayment" | "debtIncome" | "budgetExpense" | "budgetIncome" | "creditCardPayment" | "creditCardTransfer" | "creditCardIncome"; "date": string; "month": number; "year": number; "userId": string; "accountId": string; "debitAccountId"?: string | null; "categoryId": string; "incomeSourceId"?: string | null; "incomeId"?: string | null; "id"?: string; "createdAt"?: string; "updatedAt"?: string } }
export type TransactionDeleteByIdParams = { "id": string }
export type TransactionDeleteByIdQuery = Record<string, never>
export type TransactionDeleteByIdBody = unknown
export type TransactionDeleteByIdResponse = { "success": boolean; "message": string; "data"?: null }
export type TransactionGetTransactionsByAccountParams = { "accountId": string }
export type TransactionGetTransactionsByAccountQuery = Record<string, never>
export type TransactionGetTransactionsByAccountBody = unknown
export type TransactionGetTransactionsByAccountResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "type": "income" | "expense" | "transfer" | "investment" | "creditCardExpense" | "debtPayment" | "debtIncome" | "budgetExpense" | "budgetIncome" | "creditCardPayment" | "creditCardTransfer" | "creditCardIncome"; "date": string; "month": number; "year": number; "userId": string; "accountId": string; "debitAccountId"?: string | null; "categoryId": string; "incomeSourceId"?: string | null; "incomeId"?: string | null; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[] }
export type TransactionGetTransactionsByCategoryParams = { "categoryId": string }
export type TransactionGetTransactionsByCategoryQuery = Record<string, never>
export type TransactionGetTransactionsByCategoryBody = unknown
export type TransactionGetTransactionsByCategoryResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "type": "income" | "expense" | "transfer" | "investment" | "creditCardExpense" | "debtPayment" | "debtIncome" | "budgetExpense" | "budgetIncome" | "creditCardPayment" | "creditCardTransfer" | "creditCardIncome"; "date": string; "month": number; "year": number; "userId": string; "accountId": string; "debitAccountId"?: string | null; "categoryId": string; "incomeSourceId"?: string | null; "incomeId"?: string | null; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[] }
export type TransactionGetTransactionsByUserParams = { "userId": string }
export type TransactionGetTransactionsByUserQuery = Record<string, never>
export type TransactionGetTransactionsByUserBody = unknown
export type TransactionGetTransactionsByUserResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "type": "income" | "expense" | "transfer" | "investment" | "creditCardExpense" | "debtPayment" | "debtIncome" | "budgetExpense" | "budgetIncome" | "creditCardPayment" | "creditCardTransfer" | "creditCardIncome"; "date": string; "month": number; "year": number; "userId": string; "accountId": string; "debitAccountId"?: string | null; "categoryId": string; "incomeSourceId"?: string | null; "incomeId"?: string | null; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[] }
export type TransactionGetTransactionsTypeByTypeParams = { "type": string }
export type TransactionGetTransactionsTypeByTypeQuery = Record<string, never>
export type TransactionGetTransactionsTypeByTypeBody = unknown
export type TransactionGetTransactionsTypeByTypeResponse = { "success": boolean; "message": string; "data": { "description": string; "amount": number | string | {  }; "type": "income" | "expense" | "transfer" | "investment" | "creditCardExpense" | "debtPayment" | "debtIncome" | "budgetExpense" | "budgetIncome" | "creditCardPayment" | "creditCardTransfer" | "creditCardIncome"; "date": string; "month": number; "year": number; "userId": string; "accountId": string; "debitAccountId"?: string | null; "categoryId": string; "incomeSourceId"?: string | null; "incomeId"?: string | null; "id"?: string; "createdAt"?: string; "updatedAt"?: string }[] }
export type TransactionsAttachmentCreateTransactionAttachmentParams = Record<string, never>
export type TransactionsAttachmentCreateTransactionAttachmentQuery = Record<string, never>
export type TransactionsAttachmentCreateTransactionAttachmentBody = { "fileUrl": string; "fileType": string; "transactionId": string; "expensesId"?: string | null }
export type TransactionsAttachmentCreateTransactionAttachmentResponse = { "success": boolean; "message": string; "data": { "fileUrl": string; "fileType": string; "transactionId": string; "expensesId"?: string | null; "id"?: string; "createdAt"?: string | string } }
export type TransactionsAttachmentGetTransactionAttachmentParams = Record<string, never>
export type TransactionsAttachmentGetTransactionAttachmentQuery = Record<string, never>
export type TransactionsAttachmentGetTransactionAttachmentBody = unknown
export type TransactionsAttachmentGetTransactionAttachmentResponse = { "success": boolean; "message": string; "data": { "fileUrl": string; "fileType": string; "transactionId": string; "expensesId"?: string | null; "id"?: string; "createdAt"?: string | string }[] }
export type TransactionsAttachmentGetTransactionAttachmentByIdParams = { "id": string }
export type TransactionsAttachmentGetTransactionAttachmentByIdQuery = Record<string, never>
export type TransactionsAttachmentGetTransactionAttachmentByIdBody = unknown
export type TransactionsAttachmentGetTransactionAttachmentByIdResponse = { "success": boolean; "message": string; "data": { "fileUrl": string; "fileType": string; "transactionId": string; "expensesId"?: string | null; "id"?: string; "createdAt"?: string | string } }
export type TransactionsAttachmentUpdateTransactionAttachmentByIdParams = { "id": string }
export type TransactionsAttachmentUpdateTransactionAttachmentByIdQuery = Record<string, never>
export type TransactionsAttachmentUpdateTransactionAttachmentByIdBody = { "fileUrl": string; "fileType": string; "transactionId": string; "expensesId"?: string | null; "id": string }
export type TransactionsAttachmentUpdateTransactionAttachmentByIdResponse = { "success": boolean; "message": string; "data": { "fileUrl": string; "fileType": string; "transactionId": string; "expensesId"?: string | null; "id"?: string; "createdAt"?: string | string } }
export type TransactionsAttachmentDeleteTransactionAttachmentByIdParams = { "id": string }
export type TransactionsAttachmentDeleteTransactionAttachmentByIdQuery = Record<string, never>
export type TransactionsAttachmentDeleteTransactionAttachmentByIdBody = unknown
export type TransactionsAttachmentDeleteTransactionAttachmentByIdResponse = { "success": boolean; "message": string; "data"?: null }
export type NotificationsGetParams = Record<string, never>
export type NotificationsGetQuery = { "page"?: string; "pageSize"?: string }
export type NotificationsGetBody = unknown
export type NotificationsGetResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type NotificationsDeleteParams = Record<string, never>
export type NotificationsDeleteQuery = Record<string, never>
export type NotificationsDeleteBody = unknown
export type NotificationsDeleteResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type NotificationsGetUnreadCountParams = Record<string, never>
export type NotificationsGetUnreadCountQuery = Record<string, never>
export type NotificationsGetUnreadCountBody = unknown
export type NotificationsGetUnreadCountResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type NotificationsGetByIdParams = { "id": string }
export type NotificationsGetByIdQuery = Record<string, never>
export type NotificationsGetByIdBody = unknown
export type NotificationsGetByIdResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type NotificationsDeleteByIdParams = { "id": string }
export type NotificationsDeleteByIdQuery = Record<string, never>
export type NotificationsDeleteByIdBody = unknown
export type NotificationsDeleteByIdResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type NotificationsUpdateByIdReadParams = { "id": string }
export type NotificationsUpdateByIdReadQuery = Record<string, never>
export type NotificationsUpdateByIdReadBody = { "isRead": boolean }
export type NotificationsUpdateByIdReadResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type NotificationsUpdateReadAllParams = Record<string, never>
export type NotificationsUpdateReadAllQuery = Record<string, never>
export type NotificationsUpdateReadAllBody = unknown
export type NotificationsUpdateReadAllResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type NotificationsGetPreferencesParams = Record<string, never>
export type NotificationsGetPreferencesQuery = Record<string, never>
export type NotificationsGetPreferencesBody = unknown
export type NotificationsGetPreferencesResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type NotificationsUpdatePreferencesParams = Record<string, never>
export type NotificationsUpdatePreferencesQuery = Record<string, never>
export type NotificationsUpdatePreferencesBody = { "emailNotifications"?: boolean; "inAppNotifications"?: boolean; "notifyExpenses"?: boolean; "notifyIncomes"?: boolean; "notifyDebts"?: boolean; "notifyBudgetAlerts"?: boolean; "notifyInvestmentAlerts"?: boolean; "notifyAccountTransfers"?: boolean; "dailyDigest"?: boolean; "digestTime"?: string }
export type NotificationsUpdatePreferencesResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type ReportsGetDashboardParams = Record<string, never>
export type ReportsGetDashboardQuery = { "month": number; "year": number }
export type ReportsGetDashboardBody = unknown
export type ReportsGetDashboardResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type ReportsGetEvolutionParams = Record<string, never>
export type ReportsGetEvolutionQuery = { "year"?: number }
export type ReportsGetEvolutionBody = unknown
export type ReportsGetEvolutionResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type ReportsGetCashFlowParams = Record<string, never>
export type ReportsGetCashFlowQuery = { "dateFrom"?: string; "dateTo"?: string }
export type ReportsGetCashFlowBody = unknown
export type ReportsGetCashFlowResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type ReportsGetNetWorthParams = Record<string, never>
export type ReportsGetNetWorthQuery = Record<string, never>
export type ReportsGetNetWorthBody = unknown
export type ReportsGetNetWorthResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type ReportsGetExpenseAnalysisParams = Record<string, never>
export type ReportsGetExpenseAnalysisQuery = { "dateFrom"?: string; "dateTo"?: string }
export type ReportsGetExpenseAnalysisBody = unknown
export type ReportsGetExpenseAnalysisResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type ReportsGetIncomeAnalysisParams = Record<string, never>
export type ReportsGetIncomeAnalysisQuery = { "dateFrom"?: string; "dateTo"?: string }
export type ReportsGetIncomeAnalysisBody = unknown
export type ReportsGetIncomeAnalysisResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type ReportsGetFinancialHealthParams = Record<string, never>
export type ReportsGetFinancialHealthQuery = Record<string, never>
export type ReportsGetFinancialHealthBody = unknown
export type ReportsGetFinancialHealthResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type ReportsGetBudgetVsActualParams = Record<string, never>
export type ReportsGetBudgetVsActualQuery = { "dateFrom"?: string; "dateTo"?: string }
export type ReportsGetBudgetVsActualBody = unknown
export type ReportsGetBudgetVsActualResponse = { "success": boolean; "message": string; "errors"?: { "message": string; "path"?: string[] }[] }
export type HealthGetParams = Record<string, never>
export type HealthGetQuery = Record<string, never>
export type HealthGetBody = unknown
export type HealthGetResponse = { "status": string; "uptime"?: number; "timestamp"?: number; "database"?: string }