// Auto-generated from Swagger API
// Generated on: 2026-02-05T09:14:21.804Z
import { z } from 'zod'
import type { InvestmentGoalsCreateInvestmentGoalBodySchema, InvestmentGoalsCreateInvestmentGoalResponseSchema, InvestmentGoalsGetInvestmentGoalResponseSchema, InvestmentGoalsUpdateInvestmentGoalByIdBodySchema, InvestmentGoalsUpdateInvestmentGoalByIdResponseSchema, InvestmentGoalsDeleteInvestmentGoalByIdResponseSchema } from '@/lib/openapi/zod/InvestmentGoals'

export type InvestmentGoalsCreateInvestmentGoalResponse = z.infer<typeof InvestmentGoalsCreateInvestmentGoalResponseSchema>
export type InvestmentGoalsGetInvestmentGoalResponse = z.infer<typeof InvestmentGoalsGetInvestmentGoalResponseSchema>
export type InvestmentGoalsUpdateInvestmentGoalByIdResponse = z.infer<typeof InvestmentGoalsUpdateInvestmentGoalByIdResponseSchema>
export type InvestmentGoalsDeleteInvestmentGoalByIdResponse = z.infer<typeof InvestmentGoalsDeleteInvestmentGoalByIdResponseSchema>
export type InvestmentGoalsCreateInvestmentGoalBody = z.infer<typeof InvestmentGoalsCreateInvestmentGoalBodySchema>
export type InvestmentGoalsUpdateInvestmentGoalByIdBody = z.infer<typeof InvestmentGoalsUpdateInvestmentGoalByIdBodySchema>