// Auto-generated from Swagger API
// Generated on: 2026-02-05T09:14:22.074Z
import { z } from 'zod'
import type { TransactionsAttachmentCreateTransactionAttachmentBodySchema, TransactionsAttachmentCreateTransactionAttachmentResponseSchema, TransactionsAttachmentGetTransactionAttachmentResponseSchema, TransactionsAttachmentGetTransactionAttachmentByIdResponseSchema, TransactionsAttachmentUpdateTransactionAttachmentByIdBodySchema, TransactionsAttachmentUpdateTransactionAttachmentByIdResponseSchema, TransactionsAttachmentDeleteTransactionAttachmentByIdResponseSchema } from '@/lib/openapi/zod/TransactionsAttachment'

export type TransactionsAttachmentCreateTransactionAttachmentResponse = z.infer<typeof TransactionsAttachmentCreateTransactionAttachmentResponseSchema>
export type TransactionsAttachmentGetTransactionAttachmentResponse = z.infer<typeof TransactionsAttachmentGetTransactionAttachmentResponseSchema>
export type TransactionsAttachmentGetTransactionAttachmentByIdResponse = z.infer<typeof TransactionsAttachmentGetTransactionAttachmentByIdResponseSchema>
export type TransactionsAttachmentUpdateTransactionAttachmentByIdResponse = z.infer<typeof TransactionsAttachmentUpdateTransactionAttachmentByIdResponseSchema>
export type TransactionsAttachmentDeleteTransactionAttachmentByIdResponse = z.infer<typeof TransactionsAttachmentDeleteTransactionAttachmentByIdResponseSchema>
export type TransactionsAttachmentCreateTransactionAttachmentBody = z.infer<typeof TransactionsAttachmentCreateTransactionAttachmentBodySchema>
export type TransactionsAttachmentUpdateTransactionAttachmentByIdBody = z.infer<typeof TransactionsAttachmentUpdateTransactionAttachmentByIdBodySchema>